### ISSUE TITLE
Write main.js in Scala.Js

### ISSUE THREAD

**Issue by mkotsbak** [bchazalet/scalajs-electron-skeleton#1]
Is there any problems writing the main.js also in sjs? Maybe we should have had a Electron sjs wrapper?

**Comment by bchazalet** [comment]
That's a good point. I really just combined the electron hello world and
the Scala.js one for now. But we should be able to write the whole thing in
Scala.js.

**Comment by bchazalet** [comment]
It means I need the scala.js compilation must have two targets, one for the main process (e.g. main.js) and one for the renderer process (embedded in the index.html).

@mkotsbak Is there any example out there of how to do that?

**Comment by mkotsbak** [comment]
I'm not sure. Maybe you need two separate projects?

Or could you just have an exported JS function that you call from main.js if you accept a little Js?

Main win I think would be to have a wrapper for creating the main window etc.

**Comment by bchazalet** [comment]
Done, it could still be improved by creating a facade for BrowserWindow but at least now the main.js is generated by Scalajs and sbt.

**Comment by bchazalet** [comment]
I have also added -largely untested- facades for BrowserWindow and App now

**Comment by mkotsbak** [comment]
Nice. Soon time to make a library out of the wrappers.
