### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mseddon** [bchazalet/scalajs-electron-skeleton#2]
Hi.  I am looking at possibly building an electron sbt plugin and facade that will generate the require/define fixes you have implemented to coax Scala.js to work correctly with electron.  Would it be okay to use this javascript in my own project?

**Comment by bchazalet** [comment]
yes, feel free to re-use any part you like.

**Comment by mseddon** [comment]
Thanks! Naturally I will attribute you and let you know if/when I release it.
